FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine
ARG DHSYS_NUGET_KEY
ARG GITHUB_TOKEN
WORKDIR /DHsys
COPY . .
RUN dotnet tool restore && dotnet tool install -g paket
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet fake -v run ./buildPackages.fsx
ENTRYPOINT [ "dotnet","fake","run","deploy.fsx" ]