language: csharp
services:
  - docker
dotnet:
  - 3.1.301
before_install:
  - docker run --name dhsysdb -p 2424:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dhsysdb_dev -d postgres
  - docker cp database/initial.sql dhsysdb:/docker-entrypoint-initdb.d/initial.sql
  - docker exec dhsysdb psql -U postgres -f /docker-entrypoint-initdb.d/initial.sql
script:  
  - dotnet test  
