language: csharp
services:
  - docker
dotnet:
  - 3.1.301
before_install:
  - docker run --name dhsysdb -p 2424:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dhsysdb_dev -d postgres
  - dotnet tool install --global dotnet-ef
  - dotnet ef database update -p src/Libraries/DAL/ -s src/Libraries/DAL/
script:  
  - dotnet test  
