# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- upstream
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'vs2017-win2016'
pool:
  vmImage: $(imageName)

steps:
- task: Docker@2
  displayName: Build Libraries
  inputs:
    command: build
    Dockerfile: Dockerfile.ci.libraries
- task: DockerCompose@0
  displayName: Run Api tests
  inputs:
    dockerComposeFile: docker-compose.yml
    qualifyImageNames: true
    buildImages: true
    workDir: ./tests/IntegrationTests/Api.Tests/
- task: Docker@2
  displayName: Build Desktop
  inputs:
    command: build
    Dockerfile: Dockerfile.ci.desktop
#TODO: execute F# fake build script for api, docker image build is alreadly triggered on Docker hub
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Pago pelo Uso (896897bf-53c5-46eb-9f45-5c90d6f67fab)'
    KeyVaultName: 'adnanioricce-dev-keys'
    SecretsFilter: '*'
- task: DownloadSecureFile@1
  displayName: 'Get the pfx certificate'
  name: signingCertPath
  inputs:
    secureFile: 'DHsys.pfx'