apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhsysapi
spec:
  selector:
    matchLabels:
      app: dhsysapi
  replicas: 2
  template: 
    metadata:
      labels:
        app: dhsysapi
    spec:
      containers:
      - name: dhsysapi
        image: adnanioricce/dhsys
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dhsysapi
spec:
 type: NodePort
 selector:
   app: dhsysapi
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080 