FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809
WORKDIR /src
ARG GITHUB_TOKEN
RUN dotnet tool install fake-cli -g && dotnet tool install -g paket
ENV PATH="${PATH}:/root/.dotnet/tools"
ENV github_token="${GITHUB_TOKEN}"
COPY . .
RUN fake run ./CI_CD/buildDesktop.fsx
RUN fake run ./CI_CD/deployDesktop.fsx 