FROM mcr.microsoft.com/dotnet/sdk:5.0
RUN git clone https://github.com/adnanioricce/DHsys.git
WORKDIR /DHsys
RUN dotnet tool install fake-cli -g && dotnet tool install -g paket
ENV PATH="${PATH}:/root/.dotnet/tools"
# COPY . .
RUN fake run ./buildPackages.fsx