FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809
WORKDIR /src
RUN dotnet tool install fake-cli -g && dotnet tool install -g paket
ENV PATH="${PATH}:/root/.dotnet/tools"
COPY . .
RUN fake run ./CI_CD/buildDesktop.fsx 