FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809
WORKDIR /src
ARG GITHUB_TOKEN
RUN dotnet tool install fake-cli -g && dotnet tool install -g paket
ENV setx PATH "%PATH%;C:\\Users\\ContainerUser\\.dotnet\\tools"
ENV github_token="${GITHUB_TOKEN}"
COPY . .
RUN fake run ./buildDesktop.fsx
# TODO: finish the deploy script of the desktop project
# RUN fake run ./deployDesktop.fsx