FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
COPY . .
RUN apt-get update
RUN apt-get install -y postgresql-11
RUN psql -h localhost -U postgres -c "CREATE DATABASE dhsysdb"
RUN dotnet restore tests/IntegrationTests/Api.Tests/
ENV DH_CONNECTION_STRING "User ID=postgres;Password=postgres;Host=dhsysdb;Database=dhsysdb;Port=5432;"
ENV IS_DOCKER_CONTAINER true
ENTRYPOINT ["dotnet","test","./tests/IntegrationTests/Api.Tests/"]