apiVersion: v1
kind: Service
metadata:
 name: dhsysdb-service
spec:
 type: ClusterIP
 selector:
   app: dhsysdb
 ports:
  #  - name: client
  #    protocol: TCP
    -
     port: 80
     targetPort: 5432
    #  nodePort: 32080 