CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE addresses (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "FirstAddressLine" text NULL,
        "SecondAddressLine" text NULL,
        "Zipcode" text NULL,
        "Addressnumber" text NULL,
        "City" text NULL,
        "AddressState" text NULL,
        "District" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.321036+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.321122+00:00',
        CONSTRAINT "PK_addresses" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "Billings" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "BeneficiaryId" integer NOT NULL,
        "BeneficiaryName" text NULL,
        "PersonType" integer NOT NULL,
        "EndDate" timestamp without time zone NULL,
        "Price" numeric NOT NULL,
        "Discount" numeric NULL,
        "IsPaid" boolean NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.316921+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.316977+00:00',
        CONSTRAINT "PK_Billings" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "MediaResource" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Size" bigint NOT NULL,
        "Type" integer NOT NULL,
        "SourceUrl" text NULL,
        "Caption" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.31273+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.312774+00:00',
        CONSTRAINT "PK_MediaResource" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "POSOrder" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "DiscountTotal" numeric NOT NULL,
        "PaymentMethod" integer NOT NULL,
        "HasDealWithStore" boolean NOT NULL,
        "ConsumerCode" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.308184+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.308239+00:00',
        CONSTRAINT "PK_POSOrder" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "BaseProductId" integer NULL,
        "PrCdse" text NULL,
        "ManufacturerId" integer NULL,
        "ManufacturerName" text NULL,
        "CommercialName" text NULL,
        "Classification" text NULL,
        "Dosage" text NULL,
        "AbsoluteDosageInMg" double precision NULL,
        "ActivePrinciple" text NULL,
        "LotNumber" text NULL,
        "PrescriptionNeeded" boolean NOT NULL,
        "IsPriceFixed" boolean NOT NULL,
        "DigitalBuleLink" text NULL,
        "LaboratoryCode" text NULL,
        "LaboratoryName" text NULL,
        "Ncm" text NULL,
        "QuantityInStock" integer NOT NULL,
        "LastStockEntry" timestamp with time zone NULL,
        "ReorderLevel" integer NOT NULL,
        "ReorderQuantity" integer NOT NULL,
        "EndCustomerPrice" numeric NOT NULL,
        "CostPrice" numeric NOT NULL,
        "SavingPercentage" numeric NOT NULL,
        "BarCode" text NULL,
        "Description" text NULL,
        "Section" text NULL,
        "MaxDiscountPercentage" numeric NOT NULL,
        "DiscountValue" numeric NOT NULL,
        "Commission" text NULL,
        "ICMS" numeric NOT NULL,
        "MinimumStock" integer NOT NULL,
        "MainSupplierName" text NULL,
        "Name" text NULL,
        "RegistryCode" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.403772+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.403828+00:00',
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "Syncronization" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "UpdatedFrom" text NULL,
        "LastSyncronization" timestamp with time zone NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.034872+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.046775+00:00',
        CONSTRAINT "PK_Syncronization" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE beneficiaries (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "AddressId" integer NOT NULL,
        "Discriminator" text NOT NULL,
        "Cpf" character varying(12) NULL,
        "Cnpj" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.390661+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.390726+00:00',
        CONSTRAINT "PK_beneficiaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_beneficiaries_addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES addresses ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "Supplier" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AddressId" integer NULL,
        "Name" text NULL,
        "Cnpj" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.298688+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.298759+00:00',
        CONSTRAINT "PK_Supplier" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Supplier_addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES addresses ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "POSOrderItem" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ProductUniqueCode" text NULL,
        "ProductId" integer NULL,
        "Quantity" integer NOT NULL,
        "CustomerValue" numeric NOT NULL,
        "CostPrice" numeric NOT NULL,
        "POSOrderId" integer NOT NULL,
        "POSOrderId1" integer NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.31226+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.312319+00:00',
        CONSTRAINT "PK_POSOrderItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_POSOrderItem_POSOrder_POSOrderId" FOREIGN KEY ("POSOrderId") REFERENCES "POSOrder" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_POSOrderItem_POSOrder_POSOrderId1" FOREIGN KEY ("POSOrderId1") REFERENCES "POSOrder" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_POSOrderItem_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "Category" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Description" text NULL,
        "ShowOnHomepage" boolean NOT NULL,
        "ParentId" integer NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.391294+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.391341+00:00',
        CONSTRAINT "PK_Category" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Category_Category_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Category" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductCategory" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CategoryId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.392431+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.392484+00:00',
        CONSTRAINT "PK_ProductCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductCategory_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ProductCategory_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductMedia" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "MediaResourceId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "IsThumbnail" boolean NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.40508+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.405138+00:00',
        CONSTRAINT "PK_ProductMedia" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductMedia_MediaResource_MediaResourceId" FOREIGN KEY ("MediaResourceId") REFERENCES "MediaResource" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ProductMedia_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductPrice" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Pricestartdate" timestamp with time zone NULL,
        "EndCustomerDrugPrice" numeric NOT NULL,
        "CostPrice" numeric NOT NULL,
        "ProductId" integer NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.40601+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.406059+00:00',
        CONSTRAINT "PK_ProductPrice" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductPrice_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductShelfLife" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "StockEntryId" integer NOT NULL,
        "StartDate" timestamp without time zone NULL,
        "EndDate" timestamp without time zone NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.406522+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.406572+00:00',
        CONSTRAINT "PK_ProductShelfLife" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductShelfLife_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductSupplier" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "SupplierId" integer NOT NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407944+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407995+00:00',
        CONSTRAINT "PK_ProductSupplier" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductSupplier_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductSupplier_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "StockEntry" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "NfNumber" text NULL,
        "NfEmissionDate" timestamp without time zone NULL,
        "Totalcost" numeric NULL,
        "SupplierId" integer NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.291622+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.291691+00:00',
        CONSTRAINT "PK_StockEntry" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockEntry_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "ProductStockEntry" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "StockEntryId" integer NOT NULL,
        "ProductMaturityDate" timestamp without time zone NULL,
        "Quantity" integer NOT NULL,
        "LotCode" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407064+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407112+00:00',
        CONSTRAINT "PK_ProductStockEntry" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductStockEntry_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductStockEntry_StockEntry_StockEntryId" FOREIGN KEY ("StockEntryId") REFERENCES "StockEntry" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE TABLE "StockChange" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ImpactingEntityId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "Type" integer NOT NULL,
        "Note" text NULL,
        "UniqueCode" text NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407064+00:00',
        "LastUpdatedOn" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '2020-12-09 20:59:45.407112+00:00',
        CONSTRAINT "PK_StockChange" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockChange_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_beneficiaries_AddressId" ON beneficiaries ("AddressId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_POSOrderItem_POSOrderId" ON "POSOrderItem" ("POSOrderId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_POSOrderItem_POSOrderId1" ON "POSOrderItem" ("POSOrderId1");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_POSOrderItem_ProductId" ON "POSOrderItem" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_Category_ParentId" ON "Category" ("ParentId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductCategory_CategoryId" ON "ProductCategory" ("CategoryId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductCategory_ProductId" ON "ProductCategory" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductMedia_MediaResourceId" ON "ProductMedia" ("MediaResourceId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductMedia_ProductId" ON "ProductMedia" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductPrice_ProductId" ON "ProductPrice" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductShelfLife_ProductId" ON "ProductShelfLife" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductStockEntry_ProductId" ON "ProductStockEntry" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductStockEntry_StockEntryId" ON "ProductStockEntry" ("StockEntryId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_StockChange_ProductId" ON "StockChange" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductSupplier_ProductId" ON "ProductSupplier" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_ProductSupplier_SupplierId" ON "ProductSupplier" ("SupplierId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_StockEntry_SupplierId" ON "StockEntry" ("SupplierId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    CREATE INDEX "IX_Supplier_AddressId" ON "Supplier" ("AddressId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201209205945_BaseCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201209205945_BaseCreate', '5.0.0-rc.1.20451.13');
    END IF;
END $$;
COMMIT;

