CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

CREATE TABLE "Address" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Address" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "AddressId" INTEGER NOT NULL,
    "FirstAddressLine" TEXT NULL,
    "SecondAddressLine" TEXT NULL,
    "Zipcode" TEXT NULL,
    "Addressnumber" TEXT NULL,
    "City" TEXT NULL,
    "AddressState" TEXT NULL,
    "District" TEXT NULL
);

CREATE TABLE "AGENDA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_AGENDA" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "CIDADE" TEXT NULL,
    "BAIRRO" TEXT NULL,
    "CEP" TEXT NULL,
    "FONE" TEXT NULL
);

CREATE TABLE "BALCON" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_BALCON" PRIMARY KEY AUTOINCREMENT,
    "BACODI" TEXT NULL,
    "BANOME" TEXT NULL,
    "BACOMI" REAL NULL,
    "BADEVOL" REAL NULL,
    "CPF" TEXT NULL,
    "SENHA" TEXT NULL,
    "COMIS_BO" REAL NULL,
    "COMIS_PER" REAL NULL,
    "COMIS_ACE" REAL NULL,
    "COMIS_VAR" REAL NULL,
    "COMIS_ETI" REAL NULL,
    "COMIS_PERC" REAL NULL,
    "COMIS_OUT" REAL NULL
);

CREATE TABLE "Billings" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Billings" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "BeneficiaryId" INTEGER NOT NULL,
    "BeneficiaryName" TEXT NULL,
    "PersonType" INTEGER NOT NULL,
    "EndDate" TEXT NULL,
    "Price" TEXT NOT NULL,
    "Discount" TEXT NULL,
    "IsPaid" INTEGER NOT NULL
);

CREATE TABLE "BRINDES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_BRINDES" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "PONTOS" REAL NULL,
    "QTDE" REAL NULL
);

CREATE TABLE "CADLAB" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CADLAB" PRIMARY KEY AUTOINCREMENT,
    "LACODI" TEXT NULL,
    "FONOME" TEXT NULL,
    "FOAPEL" TEXT NULL,
    "FOCONT" TEXT NULL,
    "FOTELE" TEXT NULL,
    "FOTEL2" TEXT NULL,
    "FOFAXE" TEXT NULL,
    "FOENDE" TEXT NULL,
    "FONUME" TEXT NULL,
    "FOCEPE" TEXT NULL,
    "FOCIDA" TEXT NULL,
    "FOBAIR" TEXT NULL,
    "FOIBGE" TEXT NULL,
    "FOESTA" TEXT NULL,
    "LAIEST" TEXT NULL,
    "LACGCE" TEXT NULL,
    "LABREV" TEXT NULL,
    "LAULTC" TEXT NULL,
    "LACOND" TEXT NULL,
    "LAPERC" REAL NULL,
    "LAULNO" TEXT NULL,
    "LATIPO" TEXT NULL,
    "NOMARQ" TEXT NULL,
    "DT_ALTER" datetime NULL
);

CREATE TABLE "CADPROM" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CADPROM" PRIMARY KEY AUTOINCREMENT,
    "LACODI" TEXT NULL,
    "FONOME" TEXT NULL,
    "FOTELE" TEXT NULL,
    "VALID" datetime NULL
);

CREATE TABLE "CAIXA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CAIXA" PRIMARY KEY AUTOINCREMENT,
    "CX_ATEND" TEXT NULL,
    "CX_DATA" datetime NULL,
    "CX_VALOR" REAL NULL,
    "CX_REC" datetime NULL,
    "CX_ADM" TEXT NULL,
    "CX_CART" REAL NULL,
    "CX_TIPO" TEXT NULL
);

CREATE TABLE "CANCDIA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CANCDIA" PRIMARY KEY AUTOINCREMENT,
    "FILIAL" TEXT NULL,
    "TICKET" TEXT NULL,
    "CODEMP" TEXT NULL,
    "CODFUN" TEXT NULL,
    "DATA" datetime NULL,
    "DATAC" datetime NULL
);

CREATE TABLE "CARTAO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CARTAO" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "PRAZO" TEXT NULL,
    "PARCEL" TEXT NULL,
    "QTDE" REAL NULL,
    "TAXA" REAL NULL
);

CREATE TABLE "CHDEVOL" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CHDEVOL" PRIMARY KEY AUTOINCREMENT,
    "CHEQUE" TEXT NULL,
    "AGENCIA" TEXT NULL,
    "BANCO" TEXT NULL,
    "CONTA" TEXT NULL,
    "VALOR" REAL NULL,
    "DATAE" datetime NULL,
    "DATA" datetime NULL,
    "CLIENTE" TEXT NULL
);

CREATE TABLE "Cheque" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Cheque" PRIMARY KEY AUTOINCREMENT,
    "CHEQUE" TEXT NULL,
    "AGENCIA" TEXT NULL,
    "BANCO" TEXT NULL,
    "CONTA" TEXT NULL,
    "VALOR" REAL NULL,
    "DATAE" datetime NULL,
    "DATA" datetime NULL,
    "SITUACAO" TEXT NULL,
    "BAIXA" TEXT NULL,
    "TICKET" TEXT NULL,
    "FILIAL" TEXT NULL,
    "TELEFONE" TEXT NULL,
    "RG" TEXT NULL,
    "OBS" TEXT NULL,
    "CLIENTE" TEXT NULL
);

CREATE TABLE "CLICHEQ" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CLICHEQ" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "DATANASC" datetime NULL,
    "CIDADE" TEXT NULL,
    "BAIRRO" TEXT NULL,
    "CEP" TEXT NULL,
    "FONE" TEXT NULL,
    "RG" TEXT NULL,
    "CPF" TEXT NULL
);

CREATE TABLE "CLIENTE" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CLIENTE" PRIMARY KEY AUTOINCREMENT,
    "CLCODI" TEXT NULL,
    "CLNOME" TEXT NULL,
    "CLENDE" TEXT NULL,
    "CLESTADO" TEXT NULL,
    "CLCEP" TEXT NULL,
    "CLTELE" TEXT NULL,
    "CLDEBI" REAL NULL,
    "CLPAGTO" REAL NULL,
    "CLLIME" REAL NULL,
    "CLCOMPRA" datetime NULL,
    "CLUPAGTO" datetime NULL,
    "CLCIDA" TEXT NULL,
    "CLDESC" TEXT NULL,
    "CLDESMED" REAL NULL,
    "CLDESPER" REAL NULL,
    "CLBAIRRO" TEXT NULL,
    "CLNASC" datetime NULL,
    "CLRG" TEXT NULL,
    "CLOBS" TEXT NULL,
    "CLCPF" TEXT NULL,
    "CLCRED" REAL NULL
);

CREATE TABLE "CliMed" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CliMed" PRIMARY KEY AUTOINCREMENT,
    "CPF_CRM" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "SEXO" TEXT NULL,
    "FONE" TEXT NULL
);

CREATE TABLE "CLIPAGO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CLIPAGO" PRIMARY KEY AUTOINCREMENT,
    "CLIENTE" TEXT NULL,
    "DATA" datetime NULL,
    "VALOR" REAL NULL,
    "CREDITO" REAL NULL
);

CREATE TABLE "CONTAS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CONTAS" PRIMARY KEY AUTOINCREMENT,
    "COD" TEXT NULL,
    "HIST" TEXT NULL
);

CREATE TABLE "CONV" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CONV" PRIMARY KEY AUTOINCREMENT,
    "FUCDEM" TEXT NULL,
    "FUCODI" TEXT NULL,
    "CVNOTA" TEXT NULL,
    "CVBALC" TEXT NULL,
    "CVDATA" datetime NULL,
    "CVVALOURV" REAL NULL,
    "CVOBSV" TEXT NULL,
    "CVTICK" TEXT NULL,
    "CVRECEITA" TEXT NULL,
    "CVDTREC" datetime NULL,
    "CVPSUSO" TEXT NULL,
    "CVENTREGA" TEXT NULL,
    "CVVALOCRZ" REAL NULL,
    "CVCOMISSAO" REAL NULL,
    "CVLIBCOM" datetime NULL,
    "CVFILIAL" TEXT NULL,
    "CVTITULAR" TEXT NULL
);

CREATE TABLE "CONVENIO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CONVENIO" PRIMARY KEY AUTOINCREMENT,
    "FUCDEM" TEXT NULL,
    "FUCODI" TEXT NULL,
    "CVNOTA" TEXT NULL,
    "CVBALC" TEXT NULL,
    "CVDATA" datetime NULL,
    "CVMESDESC" datetime NULL,
    "CVVALOURV" REAL NULL,
    "CVOBSV" TEXT NULL,
    "CVTICK" TEXT NULL,
    "CVRECEITA" TEXT NULL,
    "CVREC" TEXT NULL,
    "CVDTREC" datetime NULL,
    "CVPSUSO" TEXT NULL,
    "CVENTREGA" TEXT NULL,
    "CVVALOCRZ" REAL NULL,
    "CVCOMISSAO" REAL NULL,
    "CVLIBCOM" datetime NULL,
    "CVFILIAL" TEXT NULL,
    "CVTITULAR" TEXT NULL
);

CREATE TABLE "DEBCLI" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_DEBCLI" PRIMARY KEY AUTOINCREMENT,
    "CLCODI" TEXT NULL,
    "BACODI" TEXT NULL,
    "PRCODI" TEXT NULL,
    "CLDATA" datetime NULL,
    "CLQTDE" REAL NULL,
    "CLPAGO" TEXT NULL,
    "CLDESC" REAL NULL,
    "CLTICK" TEXT NULL,
    "CLBALC" TEXT NULL,
    "CLOBS" TEXT NULL,
    "DESCOMP" TEXT NULL,
    "COMISSAO" REAL NULL,
    "VL_PAGO" REAL NULL,
    "DT_PAGTO" datetime NULL
);

CREATE TABLE "DELIVERY" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_DELIVERY" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "DATANASC" datetime NULL,
    "CIDADE" TEXT NULL,
    "BAIRRO" TEXT NULL,
    "CEP" TEXT NULL,
    "FONE" TEXT NULL,
    "BALCON" TEXT NULL,
    "DTCAD" datetime NULL,
    "RG" TEXT NULL,
    "CPF" TEXT NULL,
    "IMPRESSO" TEXT NULL,
    "ACUMULADO" REAL NULL,
    "APOSENTADO" TEXT NULL,
    "DESCMED" REAL NULL,
    "DESCOUT" REAL NULL,
    "CLCLASSI" TEXT NULL,
    "CLOBS1" TEXT NULL,
    "CLOBS2" TEXT NULL,
    "ULT_COMPRA" datetime NULL
);

CREATE TABLE "DESPESAS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_DESPESAS" PRIMARY KEY AUTOINCREMENT,
    "DATA" datetime NULL,
    "HISTORICO" TEXT NULL,
    "VALOR" REAL NULL,
    "CAIXA" TEXT NULL
);

CREATE TABLE "EMPRESA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_EMPRESA" PRIMARY KEY AUTOINCREMENT,
    "EMCODI" TEXT NULL,
    "EMRASO" TEXT NULL,
    "EMENDE" TEXT NULL,
    "EMNUME" TEXT NULL,
    "EMCIDA" TEXT NULL,
    "EMBAIR" TEXT NULL,
    "EMESTA" TEXT NULL,
    "EMCONT" TEXT NULL,
    "EMTELE" TEXT NULL,
    "EMCGCE" TEXT NULL,
    "EMINSC" TEXT NULL,
    "EMFAX" TEXT NULL,
    "EMCEP" TEXT NULL,
    "EMFILIAL" TEXT NULL,
    "EMLIMITE" REAL NULL,
    "DES_TICK" TEXT NULL,
    "PERC_DESC" REAL NULL,
    "DES_NOTA" REAL NULL,
    "DES_FECH" REAL NULL,
    "EMPERF" TEXT NULL,
    "EMPRINT" TEXT NULL,
    "DES_PERF" REAL NULL,
    "DES_REST" REAL NULL,
    "DES_ETIC" REAL NULL,
    "DES_B" REAL NULL,
    "DES_VAR" REAL NULL,
    "DES_ACE" REAL NULL,
    "DESCPLAC" TEXT NULL,
    "LIBPERF" TEXT NULL,
    "EMCONTRATO" TEXT NULL,
    "CODGOLDEN" TEXT NULL,
    "EMDEBITO" REAL NULL,
    "EMFECH" TEXT NULL,
    "EMGCoreA" TEXT NULL,
    "EMETICO" TEXT NULL,
    "EMOBS" TEXT NULL,
    "EMOBS1" TEXT NULL,
    "EMBLOQ" TEXT NULL,
    "VIDALK" TEXT NULL,
    "VIDAAV" TEXT NULL,
    "VIDAPC" TEXT NULL,
    "IBGEEST" TEXT NULL,
    "IBGEMUN" TEXT NULL,
    "EMRECEITA" TEXT NULL
);

CREATE TABLE "ENCOMEN" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ENCOMEN" PRIMARY KEY AUTOINCREMENT,
    "ENQTDE" REAL NULL,
    "ENDATA" datetime NULL,
    "PRCODI" TEXT NULL
);

CREATE TABLE "ENT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ENT" PRIMARY KEY AUTOINCREMENT,
    "ENDATA" datetime NULL,
    "PRCODI" TEXT NULL,
    "ENQTDE" REAL NULL,
    "ENVALO" REAL NULL,
    "PRFABR" REAL NULL,
    "IMPRESSO" TEXT NULL,
    "IMPRETQ" TEXT NULL,
    "ETIQUETA" TEXT NULL,
    "SOETIQ" TEXT NULL,
    "USUARIO" TEXT NULL,
    "ESTANT" REAL NULL,
    "DESCONTO" REAL NULL,
    "DESCFIN" REAL NULL,
    "DESCREP" REAL NULL,
    "ENVALODES" REAL NULL,
    "FORNEC" TEXT NULL,
    "NOTAFIS" TEXT NULL
);

CREATE TABLE "ENTPRO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ENTPRO" PRIMARY KEY AUTOINCREMENT,
    "ENDATA" datetime NULL,
    "PRCODI" TEXT NULL,
    "ENQTDE" REAL NULL,
    "ENVALO" REAL NULL,
    "PRFABR" REAL NULL,
    "IMPRESSO" TEXT NULL,
    "IMPRETQ" TEXT NULL,
    "ETIQUETA" TEXT NULL,
    "SOETIQ" TEXT NULL,
    "USUARIO" TEXT NULL,
    "ESTANT" REAL NULL,
    "DESCONTO" REAL NULL,
    "DESCFIN" REAL NULL,
    "DESCREP" REAL NULL,
    "ENVALODES" REAL NULL,
    "FORNEC" TEXT NULL,
    "LOTE" TEXT NULL,
    "EMISSNF" datetime NULL,
    "NOTAFIS" TEXT NULL
);

CREATE TABLE "ESTQ0045" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ESTQ0045" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "PRESTQ" REAL NULL,
    "EST_MINIMO" REAL NULL,
    "SECAO" TEXT NULL,
    "PRCDSE" TEXT NULL
);

CREATE TABLE "ETIQPERF" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ETIQPERF" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRDESC1" TEXT NULL,
    "PRDESC2" TEXT NULL,
    "PRCONS" REAL NULL,
    "PRCONSF" REAL NULL
);

CREATE TABLE "ETIQPROM" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ETIQPROM" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRDESC1" TEXT NULL,
    "PRDESC2" TEXT NULL,
    "PRCONS" REAL NULL,
    "PRCONSF" REAL NULL
);

CREATE TABLE "ETIQUETA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ETIQUETA" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRDESC1" TEXT NULL,
    "PRDESC2" TEXT NULL,
    "PRCONS" REAL NULL
);

CREATE TABLE "FALTAS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FALTAS" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "DATA" datetime NULL,
    "BALCON" TEXT NULL
);

CREATE TABLE "FECHCONV" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FECHCONV" PRIMARY KEY AUTOINCREMENT,
    "FUCDEM" TEXT NULL,
    "DATA" datetime NULL,
    "VALOR" REAL NULL
);

CREATE TABLE "FILIAL" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FILIAL" PRIMARY KEY AUTOINCREMENT,
    "FILCODI" TEXT NULL,
    "FILNOME" TEXT NULL,
    "FILENDE" TEXT NULL,
    "FILCIDA" TEXT NULL,
    "FILESTA" TEXT NULL,
    "FILCONT" TEXT NULL,
    "FILTELE" TEXT NULL,
    "FILCGCE" TEXT NULL,
    "FILINSC" TEXT NULL,
    "FILFAX" TEXT NULL,
    "FILCEP" TEXT NULL,
    "SUBSEC1" TEXT NULL,
    "DESC1" REAL NULL,
    "APLICA1" TEXT NULL,
    "SUBSEC2" TEXT NULL,
    "DESC2" REAL NULL,
    "APLICA2" TEXT NULL,
    "SUBSEC3" TEXT NULL,
    "DESC3" REAL NULL,
    "APLICA3" TEXT NULL,
    "SUBSEC4" TEXT NULL,
    "DESC4" REAL NULL,
    "APLICA4" TEXT NULL,
    "SUBSEC5" TEXT NULL,
    "DESC5" REAL NULL,
    "APLICA5" TEXT NULL,
    "SUBSEC6" TEXT NULL,
    "DESC6" REAL NULL,
    "APLICA6" TEXT NULL,
    "SUBSEC7" TEXT NULL,
    "DESC7" REAL NULL,
    "APLICA7" TEXT NULL,
    "SUBSEC8" TEXT NULL,
    "DESC8" REAL NULL,
    "APLICA8" TEXT NULL,
    "SUBSEC9" TEXT NULL,
    "DESC9" REAL NULL,
    "APLICA9" TEXT NULL,
    "SUBSEC10" TEXT NULL,
    "DESC10" REAL NULL,
    "APLICA10" TEXT NULL
);

CREATE TABLE "FUNCIO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FUNCIO" PRIMARY KEY AUTOINCREMENT,
    "FUCDEM" TEXT NULL,
    "FUCODI" TEXT NULL,
    "FUNOME" TEXT NULL,
    "FUEND" TEXT NULL,
    "FUBAI" TEXT NULL,
    "FUCID" TEXT NULL,
    "FUEST" TEXT NULL,
    "FUCEP" TEXT NULL,
    "FUFONE" TEXT NULL,
    "FUSIT" TEXT NULL,
    "FUPLANO" TEXT NULL,
    "FCoreDENT" TEXT NULL,
    "FUDEPTO" TEXT NULL,
    "TOTDEBCR" REAL NULL,
    "TOTDEBSR" REAL NULL,
    "DEMITIDO" TEXT NULL,
    "DATADEMI" datetime NULL,
    "IMPRESSO" TEXT NULL,
    "FULIMITE" REAL NULL,
    "FUOBS1" TEXT NULL,
    "FUOBS2" TEXT NULL,
    "FUOBS3" TEXT NULL,
    "FUBLOQ" TEXT NULL,
    "CODGOLDEN" TEXT NULL,
    "FUDATA" datetime NULL
);

CREATE TABLE "HISTOR" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_HISTOR" PRIMARY KEY AUTOINCREMENT,
    "DISTRIB" TEXT NULL,
    "NOTAFIS" TEXT NULL,
    "VENCTO" datetime NULL,
    "RECEBTO" datetime NULL,
    "PEDIDO" TEXT NULL,
    "TOTAL" REAL NULL,
    "DESCONTO" REAL NULL
);

CREATE TABLE "IBPT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_IBPT" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "IMP1" TEXT NULL,
    "IMP2" TEXT NULL
);

CREATE TABLE "INVENT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_INVENT" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRREG" TEXT NULL,
    "PRDESC" TEXT NULL,
    "LOTE" TEXT NULL,
    "QTDE" REAL NULL,
    "TPMED" TEXT NULL
);

CREATE TABLE "LOGSYS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_LOGSYS" PRIMARY KEY AUTOINCREMENT,
    "DATA" datetime NULL,
    "USUARIO" TEXT NULL,
    "TIME" TEXT NULL,
    "NIVEL" TEXT NULL,
    "OPCAO" TEXT NULL
);

CREATE TABLE "MALCLIEN" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MALCLIEN" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "DATANASC" datetime NULL,
    "CIDADE" TEXT NULL,
    "BAIRRO" TEXT NULL,
    "CEP" TEXT NULL,
    "FONE" TEXT NULL,
    "BALCON" TEXT NULL,
    "DTCAD" datetime NULL,
    "RG" TEXT NULL,
    "CPF" TEXT NULL,
    "IMPRESSO" TEXT NULL,
    "ACUMULADO" REAL NULL,
    "APOSENTADO" TEXT NULL,
    "DESCMED" REAL NULL,
    "DESCOUT" REAL NULL,
    "CLCLASSI" TEXT NULL,
    "CLOBS1" TEXT NULL,
    "CLOBS2" TEXT NULL,
    "FILIAL" TEXT NULL,
    "ULT_COMPRA" datetime NULL
);

CREATE TABLE "MERCTRAN" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MERCTRAN" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "DESCRICAO" TEXT NULL,
    "QTDE" REAL NULL,
    "PRCONS" REAL NULL,
    "DESCONTO" REAL NULL,
    "ESTOQUE" REAL NULL,
    "ETIQUETA" TEXT NULL,
    "PRCONSD" REAL NULL,
    "COMISSAO" TEXT NULL,
    "VL_TOTAL" REAL NULL
);

CREATE TABLE "MOV" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOV" PRIMARY KEY AUTOINCREMENT,
    "N_FISCAL" TEXT NULL,
    "TICKET" TEXT NULL,
    "TOT_VEN" REAL NULL,
    "TOT_ANT" REAL NULL,
    "TIPO" TEXT NULL,
    "TPVD" TEXT NULL,
    "ECF" TEXT NULL,
    "CPF" TEXT NULL,
    "NOME" TEXT NULL,
    "DATA" datetime NULL,
    "BACODI" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "CAIXA" TEXT NULL,
    "HORA" TEXT NULL,
    "DINHEIRO" REAL NULL,
    "CHEQUE" REAL NULL,
    "CHEQUEPRE" REAL NULL,
    "CARTAOC" REAL NULL,
    "POPULAR" REAL NULL,
    "ADMCART" TEXT NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "MOVM" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOVM" PRIMARY KEY AUTOINCREMENT,
    "N_FISCAL" TEXT NULL,
    "TICKET" TEXT NULL,
    "TOT_VEN" REAL NULL,
    "TOT_ANT" REAL NULL,
    "TIPO" TEXT NULL,
    "TPVD" TEXT NULL,
    "DATA" datetime NULL,
    "BACODI" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "CAIXA" TEXT NULL,
    "HORA" TEXT NULL,
    "DINHEIRO" REAL NULL,
    "CHEQUE" REAL NULL,
    "CHEQUEPRE" REAL NULL,
    "CARTAOC" REAL NULL,
    "ADMCART" TEXT NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "MOVME" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOVME" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "VL_UNIT" REAL NULL,
    "VLLIQCoreD" REAL NULL,
    "TOT_DESCON" REAL NULL,
    "TICKET" TEXT NULL,
    "BACODI" TEXT NULL,
    "DATA" datetime NULL,
    "TIPO" TEXT NULL,
    "TPVD" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "VL_TOT" REAL NULL,
    "TOT_COMIS" REAL NULL,
    "PEDIDO" TEXT NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "MOVMES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOVMES" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "VL_UNIT" REAL NULL,
    "VLLIQCoreD" REAL NULL,
    "TOT_DESCON" REAL NULL,
    "TICKET" TEXT NULL,
    "BACODI" TEXT NULL,
    "DATA" datetime NULL,
    "TIPO" TEXT NULL,
    "TPVD" TEXT NULL,
    "ECF" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "VL_TOT" REAL NULL,
    "TOT_COMIS" REAL NULL,
    "PEDIDO" TEXT NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "MOVNF" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOVNF" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "VL_UNIT" REAL NULL,
    "TICKET" TEXT NULL,
    "DATA" datetime NULL,
    "ECF" TEXT NULL,
    "DESCRICAO" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "CPF" TEXT NULL,
    "VL_TOT" REAL NULL
);

CREATE TABLE "MOVPOP" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_MOVPOP" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "VL_UNIT" REAL NULL,
    "VLLIQCoreD" REAL NULL,
    "TOT_DESCON" REAL NULL,
    "TICKET" TEXT NULL,
    "DATA" datetime NULL,
    "DATAREC" datetime NULL,
    "ECF" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "VL_TOT" REAL NULL,
    "COMPDIA" REAL NULL,
    "COMPMES" REAL NULL,
    "BALC_CPF" TEXT NULL,
    "CPFCLI" TEXT NULL,
    "SENHA" TEXT NULL,
    "CRM" TEXT NULL
);

CREATE TABLE "NATUREZA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NATUREZA" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL
);

CREATE TABLE "NEWCLI" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NEWCLI" PRIMARY KEY AUTOINCREMENT,
    "CODIGO" TEXT NULL,
    "NOME" TEXT NULL,
    "ENDERECO" TEXT NULL,
    "CIDADE" TEXT NULL,
    "BAIRRO" TEXT NULL,
    "CEP" TEXT NULL,
    "FONE" TEXT NULL,
    "RG" TEXT NULL,
    "DATANASC" datetime NULL,
    "TIPO" TEXT NULL,
    "IMPRESSO" TEXT NULL,
    "DESCONTO" REAL NULL,
    "CLCLASSI" TEXT NULL,
    "ULT_COMPRA" datetime NULL
);

CREATE TABLE "NEWFUNC" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NEWFUNC" PRIMARY KEY AUTOINCREMENT,
    "FUCDEM" TEXT NULL,
    "FUCODI" TEXT NULL,
    "FUNOME" TEXT NULL,
    "FUEND" TEXT NULL,
    "FUBAI" TEXT NULL,
    "FUCID" TEXT NULL,
    "FUEST" TEXT NULL,
    "FUCEP" TEXT NULL,
    "FUFONE" TEXT NULL,
    "FUSIT" TEXT NULL,
    "FUDEPTO" TEXT NULL,
    "TOTDEBCR" REAL NULL,
    "TOTDEBSR" REAL NULL,
    "DEMITIDO" TEXT NULL,
    "DATADEMI" datetime NULL,
    "IMPRESSO" TEXT NULL,
    "FULIMITE" REAL NULL,
    "FUOBS1" TEXT NULL,
    "FUOBS2" TEXT NULL,
    "FUOBS3" TEXT NULL,
    "FUBLOQ" TEXT NULL,
    "CODGOLDEN" TEXT NULL,
    "FUDATA" datetime NULL
);

CREATE TABLE "NEWPREC" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NEWPREC" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRCONS" REAL NULL,
    "PRCONSCV" REAL NULL,
    "PRFABR" REAL NULL,
    "PRCDDT" datetime NULL,
    "PRCDLUCR" REAL NULL
);

CREATE TABLE "NEWPROD" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NEWPROD" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRREG" TEXT NULL,
    "PRDESC" TEXT NULL,
    "PRPOS" TEXT NULL,
    "PRSAL" TEXT NULL,
    "PRNEUTRO" TEXT NULL,
    "PRCDLA" TEXT NULL,
    "PRNOLA" TEXT NULL,
    "PRCONS" REAL NULL,
    "PRCONSCV" REAL NULL,
    "PRFABR" REAL NULL,
    "PRESTQ" REAL NULL,
    "PRTESTQ" REAL NULL,
    "PRCDSE" TEXT NULL,
    "PRLOCA" TEXT NULL,
    "CODDCB" TEXT NULL,
    "PRNOSE" TEXT NULL,
    "PRETIQ" TEXT NULL,
    "ETBARRA" TEXT NULL,
    "ETGRAF" TEXT NULL,
    "PRPRET" TEXT NULL,
    "PRPORTA" TEXT NULL,
    "PRSITU" TEXT NULL,
    "PRULTE" REAL NULL,
    "PRDTUL" datetime NULL,
    "PRCDDT" datetime NULL,
    "PRDATA" datetime NULL,
    "PRCDLUCR" REAL NULL,
    "PRICMS" REAL NULL,
    "TIPO" TEXT NULL,
    "DESC_MAX" REAL NULL,
    "COMISSAO" REAL NULL,
    "EST_MINIMO" REAL NULL,
    "PRCDIMP" TEXT NULL,
    "PRCDIMP2" TEXT NULL,
    "PREMB" REAL NULL,
    "PRENTR" REAL NULL,
    "UL_VEN" datetime NULL,
    "ULTPED" datetime NULL,
    "ULTFOR" TEXT NULL,
    "PRCLAS" TEXT NULL,
    "PRMESANT" REAL NULL,
    "PRDESCONV" TEXT NULL,
    "PRPOPULAR" TEXT NULL,
    "CODESTA" TEXT NULL,
    "CODFIS" TEXT NULL,
    "SECAO" TEXT NULL,
    "PRPIS" TEXT NULL,
    "VENDATU" REAL NULL,
    "VENDANT" REAL NULL
);

CREATE TABLE "NEWTAB" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NEWTAB" PRIMARY KEY AUTOINCREMENT,
    "NEWTAB" TEXT NULL,
    "MESANO" TEXT NULL
);

CREATE TABLE "NFE" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NFE" PRIMARY KEY AUTOINCREMENT,
    "CAMPO" TEXT NULL,
    "CODIGO" TEXT NULL,
    "DESCRICAO" TEXT NULL,
    "QTDE" TEXT NULL,
    "VALOR" TEXT NULL,
    "VLTOT" TEXT NULL,
    "NCM" TEXT NULL,
    "IMP" TEXT NULL,
    "ICMS" TEXT NULL,
    "PRCDIMP" TEXT NULL
);

CREATE TABLE "NOTA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NOTA" PRIMARY KEY AUTOINCREMENT,
    "N_FISCAL" TEXT NULL,
    "CLIENTE" TEXT NULL,
    "NVALOR" REAL NULL,
    "BASE" REAL NULL,
    "ICMS" REAL NULL,
    "BASESUB" REAL NULL,
    "ICMSSUB" REAL NULL,
    "NBASE7" REAL NULL,
    "NICMS7" REAL NULL,
    "NBASE12" REAL NULL,
    "NICMS12" REAL NULL,
    "NBASE18" REAL NULL,
    "NICMS18" REAL NULL,
    "NBASE25" REAL NULL,
    "NICMS25" REAL NULL,
    "NATUREZA" TEXT NULL,
    "N_NATU" TEXT NULL,
    "NDATA" datetime NULL,
    "NCANCELADA" TEXT NULL
);

CREATE TABLE "NOTAF" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NOTAF" PRIMARY KEY AUTOINCREMENT,
    "NUM_NOTA" TEXT NULL
);

CREATE TABLE "NPED" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NPED" PRIMARY KEY AUTOINCREMENT,
    "NUMPED" TEXT NULL
);

CREATE TABLE "NUMPED" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NUMPED" PRIMARY KEY AUTOINCREMENT,
    "FORNEC" TEXT NULL,
    "PRZPAGTO" TEXT NULL,
    "DESCONTO" REAL NULL,
    "NUMERO" TEXT NULL,
    "PRZENTREGA" TEXT NULL
);

CREATE TABLE "NumTmp" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_NumTmp" PRIMARY KEY AUTOINCREMENT,
    "NUMERO" TEXT NULL
);

CREATE TABLE "PED0204" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED0204" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PED0301" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED0301" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PED0406" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED0406" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PED1103" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED1103" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PED1406" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED1406" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PED1912" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PED1912" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRDESC" TEXT NULL,
    "CODINT" TEXT NULL,
    "MLOJA1" REAL NULL,
    "ELOJA1" REAL NULL,
    "NLOJA1" REAL NULL,
    "MLOJA2" REAL NULL,
    "ELOJA2" REAL NULL,
    "NLOJA2" REAL NULL,
    "MLOJA3" REAL NULL,
    "ELOJA3" REAL NULL,
    "NLOJA3" REAL NULL,
    "MLOJA4" REAL NULL,
    "ELOJA4" REAL NULL,
    "NLOJA4" REAL NULL,
    "VALOR" REAL NULL,
    "FORN" TEXT NULL
);

CREATE TABLE "PEDIDOS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PEDIDOS" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "PRCDLA" TEXT NULL,
    "PRFABR" REAL NULL,
    "STATUS" TEXT NULL,
    "PRDATA" datetime NULL
);

CREATE TABLE "PRODEXTR" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PRODEXTR" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRDESC" TEXT NULL,
    "PRCONS" REAL NULL,
    "CONCOR1" REAL NULL,
    "CONCOR2" REAL NULL,
    "CONCOR3" REAL NULL,
    "CONCOR4" REAL NULL
);

CREATE TABLE "PRODUTO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PRODUTO" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "PRCODI" TEXT NULL,
    "PRBARRA" TEXT NULL,
    "PRREG" TEXT NULL,
    "PRDESC" TEXT NULL,
    "PRLOTE" TEXT NULL,
    "PRPOS" TEXT NULL,
    "PRSAL" TEXT NULL,
    "PRNEUTRO" TEXT NULL,
    "PRCDLA" TEXT NULL,
    "PRNOLA" TEXT NULL,
    "PRCONS" REAL NULL,
    "PRCONSCV" REAL NULL,
    "PRFABR" REAL NULL,
    "PRFIXA" TEXT NULL,
    "PRPROMO" REAL NULL,
    "VLCOMIS" REAL NULL,
    "PRESTQ" REAL NULL,
    "PRINICIAL" REAL NULL,
    "PRFINAL" REAL NULL,
    "PRTESTQ" REAL NULL,
    "PRCDSE" TEXT NULL,
    "PRLOCA" TEXT NULL,
    "PRNOSE" TEXT NULL,
    "PRETIQ" TEXT NULL,
    "CODDCB" TEXT NULL,
    "ETBARRA" TEXT NULL,
    "ETGRAF" TEXT NULL,
    "PRPRET" TEXT NULL,
    "PRPORTA" TEXT NULL,
    "PRSITU" TEXT NULL,
    "PRULTE" REAL NULL,
    "PRDTUL" datetime NULL,
    "PRCDDT" datetime NULL,
    "PRDATA" datetime NULL,
    "PRCDLUCR" REAL NULL,
    "PRICMS" REAL NULL,
    "TIPO" TEXT NULL,
    "DESC_MAX" REAL NULL,
    "COMISSAO" REAL NULL,
    "EST_MINIMO" REAL NULL,
    "PRCDIMP" TEXT NULL,
    "PRCDIMP2" TEXT NULL,
    "PREMB" REAL NULL,
    "PRENTR" REAL NULL,
    "UL_VEN" datetime NULL,
    "ULTPED" datetime NULL,
    "ULTFOR" TEXT NULL,
    "PRCLAS" TEXT NULL,
    "PRMESANT" REAL NULL,
    "ULTPRECO" REAL NULL,
    "PRDESCONV" TEXT NULL,
    "PRPOPULAR" TEXT NULL,
    "CODESTA" TEXT NULL,
    "PRPRINCI" TEXT NULL,
    "CODFIS" TEXT NULL,
    "SECAO" TEXT NULL,
    "PRPIS" TEXT NULL,
    "PRUN" TEXT NULL,
    "PRNCMS" TEXT NULL,
    "PRVALID" datetime NULL,
    "VENDATU" REAL NULL,
    "VENDANT" REAL NULL
);

CREATE TABLE "PSICO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PSICO" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "TICKET" TEXT NULL,
    "PRREG" TEXT NULL,
    "BARRAS" TEXT NULL,
    "PRDESC" TEXT NULL,
    "RECEITA" TEXT NULL,
    "TPRECEITA" TEXT NULL,
    "CRM" TEXT NULL,
    "NOMEMED" TEXT NULL,
    "TPCONS" TEXT NULL,
    "UFCONS" TEXT NULL,
    "LOTE" TEXT NULL,
    "QTDE" REAL NULL,
    "DATA" datetime NULL,
    "TIPO" TEXT NULL,
    "MOTIVO" TEXT NULL,
    "USOMED" TEXT NULL,
    "PORTA" TEXT NULL,
    "RG" TEXT NULL,
    "ORGAO" TEXT NULL,
    "PACIENTE" TEXT NULL,
    "UF" TEXT NULL,
    "EMISSAO" datetime NULL,
    "NF" TEXT NULL,
    "CNPJ" TEXT NULL,
    "FORNEC" TEXT NULL,
    "FONE" TEXT NULL,
    "NOME" TEXT NULL,
    "TPMED" TEXT NULL,
    "SEXO" TEXT NULL,
    "CID" TEXT NULL,
    "IDADE" TEXT NULL,
    "TPIDADE" TEXT NULL,
    "PROLONG" TEXT NULL,
    "UNIDADE" TEXT NULL,
    "NASC" datetime NULL
);

CREATE TABLE "RANCLIQT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_RANCLIQT" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "PRQTDE" REAL NULL,
    "VL_UNIT" REAL NULL,
    "TOT_DESCON" REAL NULL,
    "TICKET" TEXT NULL,
    "BACODI" TEXT NULL,
    "DATA" datetime NULL,
    "TIPO" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "VL_TOT" REAL NULL,
    "TOT_COMIS" REAL NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "RANCLIVL" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_RANCLIVL" PRIMARY KEY AUTOINCREMENT,
    "N_FISCAL" TEXT NULL,
    "TICKET" TEXT NULL,
    "TOT_VEN" REAL NULL,
    "TIPO" TEXT NULL,
    "DATA" datetime NULL,
    "BACODI" TEXT NULL,
    "CANCELADO" TEXT NULL,
    "CAIXA" TEXT NULL,
    "HORA" TEXT NULL,
    "CODCLI" TEXT NULL
);

CREATE TABLE "RECONST" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_RECONST" PRIMARY KEY AUTOINCREMENT,
    "ARQCoreVO" TEXT NULL,
    "POSICAO" TEXT NULL,
    "DATA" datetime NULL,
    "NECESSITA" TEXT NULL
);

CREATE TABLE "REDUCAO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_REDUCAO" PRIMARY KEY AUTOINCREMENT,
    "RZAUT" TEXT NULL,
    "GTDA" TEXT NULL,
    "CANCELA" TEXT NULL,
    "DESCONTO" TEXT NULL,
    "TRIBUTO" TEXT NULL,
    "SUPRI" TEXT NULL,
    "NSI" TEXT NULL,
    "CNSI" TEXT NULL,
    "COO" TEXT NULL,
    "CNS" TEXT NULL,
    "ALIQUOTA" TEXT NULL,
    "DATA" TEXT NULL,
    "ACRESC" TEXT NULL,
    "ACRESFIN" TEXT NULL,
    "SANGRIA" TEXT NULL
);

CREATE TABLE "relator" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_relator" PRIMARY KEY AUTOINCREMENT,
    "RELATORIO" TEXT NULL,
    "NIVEL" TEXT NULL
);

CREATE TABLE "ResAno" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ResAno" PRIMARY KEY AUTOINCREMENT,
    "MES_REF" TEXT NULL,
    "CLI_ATDS" REAL NULL,
    "VEN_MES" REAL NULL,
    "TOT_ESTOQ" REAL NULL,
    "DIASTRAB" REAL NULL,
    "ENTRADAS" REAL NULL,
    "DESCREC" REAL NULL,
    "VEN_FIADO" REAL NULL,
    "REC_FIADO" REAL NULL,
    "VDA_VISTA" REAL NULL,
    "VDA_CONV" REAL NULL
);

CREATE TABLE "RETIRADA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_RETIRADA" PRIMARY KEY AUTOINCREMENT,
    "DATA" datetime NULL,
    "VALORDH" REAL NULL,
    "VALORCH" REAL NULL,
    "HORA" TEXT NULL,
    "CAIXA" TEXT NULL
);

CREATE TABLE "SAL" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SAL" PRIMARY KEY AUTOINCREMENT,
    "SALCOD" TEXT NULL,
    "SALNOME" TEXT NULL
);

CREATE TABLE "SECAO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SECAO" PRIMARY KEY AUTOINCREMENT,
    "SECODI" TEXT NULL,
    "SENOME" TEXT NULL
);

CREATE TABLE "SENHA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SENHA" PRIMARY KEY AUTOINCREMENT,
    "SEN" TEXT NULL,
    "SENCHEQ" TEXT NULL,
    "SENCIT" TEXT NULL,
    "SENCLICH" TEXT NULL,
    "SENCLIP" TEXT NULL,
    "SENCONT" TEXT NULL,
    "SENDATE" datetime NULL,
    "SENDEFA" TEXT NULL,
    "SENDESC" REAL NULL,
    "SENDESC1" REAL NULL,
    "SENDESC2" REAL NULL,
    "SENDESC3" REAL NULL,
    "SENDESC4" REAL NULL,
    "SENDESC5" REAL NULL,
    "SENDESC6" REAL NULL,
    "SENDIA" REAL NULL,
    "SENESTQ" TEXT NULL,
    "SENETQ" TEXT NULL,
    "SENETQB" TEXT NULL,
    "SENETQE" TEXT NULL,
    "SENETQP" TEXT NULL,
    "SENFIA" TEXT NULL,
    "SENFIACR" REAL NULL,
    "SENFIATR" REAL NULL,
    "SENFIS" TEXT NULL,
    "SENLIN" REAL NULL,
    "SENMAN" TEXT NULL,
    "SENMDPRINT" REAL NULL,
    "SENMULTA" REAL NULL,
    "SENNIV" TEXT NULL,
    "SENPAR" TEXT NULL,
    "SENPCLI" datetime NULL,
    "SENPME" REAL NULL,
    "SENPONTO" REAL NULL,
    "SENPORT" TEXT NULL,
    "SENPRINT" TEXT NULL,
    "SENPROT" TEXT NULL,
    "SENREC" TEXT NULL,
    "SENREL" TEXT NULL,
    "SENREPETE" TEXT NULL,
    "SENVER" TEXT NULL,
    "SENVLPON" REAL NULL
);

CREATE TABLE "SERVICO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SERVICO" PRIMARY KEY AUTOINCREMENT,
    "SVCODI" TEXT NULL,
    "SVDESC" TEXT NULL,
    "SVPREC" REAL NULL,
    "SVVEN1" REAL NULL,
    "SVVEN2" REAL NULL,
    "SVCOMB" REAL NULL,
    "SVPR01" TEXT NULL,
    "SVPR02" TEXT NULL,
    "SVPR03" TEXT NULL,
    "SVPR04" TEXT NULL,
    "SVPR05" TEXT NULL
);

CREATE TABLE "SISTEMA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SISTEMA" PRIMARY KEY AUTOINCREMENT,
    "USUARIO" TEXT NULL,
    "TICKET" TEXT NULL
);

CREATE TABLE "SLPHARMA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SLPHARMA" PRIMARY KEY AUTOINCREMENT,
    "RECONST" TEXT NULL
);

CREATE TABLE "SUBSECAO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SUBSECAO" PRIMARY KEY AUTOINCREMENT,
    "SUBSECODI" TEXT NULL,
    "SUBSENOME" TEXT NULL,
    "SUBSEPREC" TEXT NULL,
    "SECAOPERT" TEXT NULL,
    "SUBSELUCR" REAL NULL,
    "VALREC" REAL NULL,
    "SUBIMPOST" REAL NULL,
    "SUBNCM" TEXT NULL
);

CREATE TABLE "TABELA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TABELA" PRIMARY KEY AUTOINCREMENT,
    "ABC" TEXT NULL,
    "CTR" TEXT NULL,
    "NOM" TEXT NULL,
    "DES" TEXT NULL,
    "PLA1" REAL NULL,
    "PCO1" REAL NULL,
    "FRA1" REAL NULL,
    "UNI" REAL NULL,
    "IPI" REAL NULL,
    "DTVIG" datetime NULL,
    "NEUTRO" TEXT NULL,
    "NEGPOS" TEXT NULL,
    "CUSTOM" TEXT NULL,
    "MED_DES" TEXT NULL,
    "MED_APR" TEXT NULL,
    "MED_PRINCI" TEXT NULL,
    "MED_REGIMS" TEXT NULL,
    "LAB_NOM" TEXT NULL,
    "BARRA" REAL NULL
);

CREATE TABLE "TEMP" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TEMP" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "DESCRICAO" TEXT NULL,
    "PRCONS" REAL NULL,
    "DESCONTO" REAL NULL,
    "PRCONSD" REAL NULL,
    "VL_TOTAL" REAL NULL,
    "QTDE" REAL NULL
);

CREATE TABLE "TEMPO" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TEMPO" PRIMARY KEY AUTOINCREMENT,
    "PRCODI" TEXT NULL,
    "DESCRICAO" TEXT NULL,
    "QTDE" REAL NULL,
    "PRCONS" REAL NULL,
    "DESCONTO" REAL NULL,
    "ESTOQUE" REAL NULL,
    "PEDIDO" TEXT NULL,
    "PRCONSD" REAL NULL,
    "VL_TOTAL" REAL NULL
);

CREATE TABLE "TICKET" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TICKET" PRIMARY KEY AUTOINCREMENT,
    "TICKET" TEXT NULL,
    "ECF" TEXT NULL
);

CREATE TABLE "TRANSFER" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TRANSFER" PRIMARY KEY AUTOINCREMENT,
    "TRDATA" datetime NULL,
    "BALCON" TEXT NULL,
    "PRCODI" TEXT NULL,
    "QTDE" REAL NULL,
    "PRCONS" REAL NULL,
    "ETIQUETA" TEXT NULL,
    "IMPRESSO" TEXT NULL,
    "FILCODI" TEXT NULL,
    "HORA" TEXT NULL
);

CREATE TABLE "TROCO1" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO1" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO10" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO10" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO11" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO11" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO12" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO12" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO13" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO13" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO14" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO14" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO15" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO15" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO16" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO16" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO17" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO17" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO18" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO18" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO19" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO19" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO2" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO2" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO20" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO20" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO3" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO3" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO4" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO4" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO5" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO5" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO6" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO6" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO7" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO7" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO8" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO8" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "TROCO9" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TROCO9" PRIMARY KEY AUTOINCREMENT,
    "TROCO_INI" REAL NULL,
    "INITROCO" TEXT NULL,
    "DATA" datetime NULL
);

CREATE TABLE "URV" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_URV" PRIMARY KEY AUTOINCREMENT,
    "DATA" datetime NULL,
    "VALOR" REAL NULL
);

CREATE TABLE "USEFARMA" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_USEFARMA" PRIMARY KEY AUTOINCREMENT,
    "NOME" TEXT NULL,
    "SENHA" TEXT NULL,
    "NIVEL" TEXT NULL,
    "ACESSO1" TEXT NULL,
    "ACESSO2" TEXT NULL,
    "ACESSO3" TEXT NULL,
    "ACESSO4" TEXT NULL,
    "ACESSO5" TEXT NULL,
    "ACESSO6" TEXT NULL,
    "ACESSO7" TEXT NULL,
    "ACESSO8" TEXT NULL,
    "ACESSO9" TEXT NULL,
    "ACESSO10" TEXT NULL
);

CREATE TABLE "USOINT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_USOINT" PRIMARY KEY AUTOINCREMENT,
    "DATA" datetime NULL,
    "PRCODI" TEXT NULL,
    "QTDE" REAL NULL
);

CREATE TABLE "Client" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Client" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "Name" TEXT NULL,
    "AddressId" INTEGER NULL,
    "Cpf" TEXT NULL,
    CONSTRAINT "FK_Client_Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Address" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Manufacturers" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Manufacturers" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "Name" TEXT NULL,
    "AddressId" INTEGER NULL,
    "Cnpj" TEXT NULL,
    CONSTRAINT "FK_Manufacturers_Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Address" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Supplier" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Supplier" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "AddressId" INTEGER NULL,
    "SupplierName" TEXT NULL,
    "Cnpj" TEXT NULL,
    CONSTRAINT "FK_Supplier_Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Address" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StockEntries" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_StockEntries" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "SupplierId" INTEGER NULL,
    "Quantity" INTEGER NULL,
    "CreatedAt" TEXT NULL,
    "DrugMaturityDate" TEXT NULL,
    "NfNumber" TEXT NULL,
    "NfEmissionDate" TEXT NULL,
    "Totalcost" TEXT NULL,
    "LotCode" TEXT NULL,
    CONSTRAINT "FK_StockEntries_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Products" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Products" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "Ncm" TEXT NULL,
    "QuantityInStock" INTEGER NULL,
    "ReorderLevel" INTEGER NULL,
    "ReorderQuantity" INTEGER NULL,
    "EndCustomerPrice" TEXT NULL,
    "CostPrice" TEXT NOT NULL,
    "SavingPercentage" TEXT NOT NULL,
    "BarCode" TEXT NULL,
    "Description" TEXT NULL,
    "Section" TEXT NULL,
    "MaxDiscountPercentage" TEXT NOT NULL,
    "DiscountValue" TEXT NOT NULL,
    "Commission" TEXT NULL,
    "ICMS" TEXT NOT NULL,
    "MinimumStock" INTEGER NOT NULL,
    "MainSupplierName" TEXT NULL,
    "ProdutoId" INTEGER NULL,
    "Discriminator" TEXT NOT NULL,
    "BaseDrugId" INTEGER NULL,
    "SupplierId" INTEGER NULL,
    "PrCdse" TEXT NULL,
    "ManufacturerId" INTEGER NULL,
    "ManufacturerName" TEXT NULL,
    "DrugName" TEXT NULL,
    "CommercialName" TEXT NULL,
    "Classification" TEXT NULL,
    "DrugCost" TEXT NULL,
    "Dosage" TEXT NULL,
    "AbsoluteDosageInMg" REAL NULL,
    "ActivePrinciple" TEXT NULL,
    "LotNumber" TEXT NULL,
    "PrescriptionNeeded" INTEGER NULL,
    "IsPriceFixed" INTEGER NULL,
    "DigitalBuleLink" TEXT NULL,
    "StockEntryId" INTEGER NULL,
    CONSTRAINT "FK_Products_StockEntries_StockEntryId" FOREIGN KEY ("StockEntryId") REFERENCES "StockEntries" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Products_PRODUTO_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "PRODUTO" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DrugInformation" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_DrugInformation" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "DrugId" INTEGER NULL,
    "Indication" TEXT NULL,
    "CounterIndication" TEXT NULL,
    "HowWorks" TEXT NULL,
    "HowToUse" TEXT NULL,
    "TypeOfUse" TEXT NULL,
    "MinimalAgeOfUse" INTEGER NULL,
    "Substances" TEXT NULL,
    "UserBule" TEXT NULL,
    "ProfessionalBule" TEXT NULL,
    CONSTRAINT "FK_DrugInformation_Products_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductPrice" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ProductPrice" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "Pricestartdate" TEXT NULL,
    "EndCustomerDrugPrice" TEXT NOT NULL,
    "CostPrice" TEXT NOT NULL,
    CONSTRAINT "FK_ProductPrice_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductShelfLife" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ProductShelfLife" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "StockEntryId" INTEGER NOT NULL,
    "StartDate" TEXT NULL,
    "EndDate" TEXT NULL,
    CONSTRAINT "FK_ProductShelfLife_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductStockEntry" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ProductStockEntry" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "StockEntryId" INTEGER NOT NULL,
    CONSTRAINT "FK_ProductStockEntry_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductStockEntry_StockEntries_StockEntryId" FOREIGN KEY ("StockEntryId") REFERENCES "StockEntries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProductSupplier" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ProductSupplier" PRIMARY KEY AUTOINCREMENT,
    "UniqueCode" TEXT NULL,
    "LastUpdatedOn" TEXT NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "SupplierId" INTEGER NOT NULL,
    CONSTRAINT "FK_ProductSupplier_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProductSupplier_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Supplier" ("Id") ON DELETE CASCADE
);

INSERT INTO "Billings" ("Id", "BeneficiaryId", "BeneficiaryName", "Discount", "EndDate", "IsPaid", "LastUpdatedOn", "PersonType", "Price", "UniqueCode")
VALUES (1, 0, 'empresa', NULL, '2020-05-20 02:37:05.6866182', 0, '2020-05-20 02:37:05.6865567+00:00', 0, '12.99', NULL);

INSERT INTO "Billings" ("Id", "BeneficiaryId", "BeneficiaryName", "Discount", "EndDate", "IsPaid", "LastUpdatedOn", "PersonType", "Price", "UniqueCode")
VALUES (2, 0, 'empresa 2', NULL, '2020-05-20 02:37:05.6868372', 0, '2020-05-20 02:37:05.6868355+00:00', 0, '22.99', NULL);

CREATE INDEX "IX_Client_AddressId" ON "Client" ("AddressId");

CREATE INDEX "IX_DrugInformation_DrugId" ON "DrugInformation" ("DrugId");

CREATE INDEX "IX_Manufacturers_AddressId" ON "Manufacturers" ("AddressId");

CREATE INDEX "IX_ProductPrice_ProductId" ON "ProductPrice" ("ProductId");

CREATE INDEX "IX_Products_StockEntryId" ON "Products" ("StockEntryId");

CREATE INDEX "IX_Products_ProdutoId" ON "Products" ("ProdutoId");

CREATE INDEX "IX_ProductShelfLife_ProductId" ON "ProductShelfLife" ("ProductId");

CREATE INDEX "IX_ProductStockEntry_ProductId" ON "ProductStockEntry" ("ProductId");

CREATE INDEX "IX_ProductStockEntry_StockEntryId" ON "ProductStockEntry" ("StockEntryId");

CREATE INDEX "IX_ProductSupplier_ProductId" ON "ProductSupplier" ("ProductId");

CREATE INDEX "IX_ProductSupplier_SupplierId" ON "ProductSupplier" ("SupplierId");

CREATE INDEX "IX_StockEntries_SupplierId" ON "StockEntries" ("SupplierId");

CREATE INDEX "IX_Supplier_AddressId" ON "Supplier" ("AddressId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200520023707_InitialCreate', '3.1.3');

