name: 'cd'
on:
  push:
    branches:      
      - master
jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet: '5.0.x'
      - name: Install FAKE
        run: dotnet tool restore
      - name: Run script
        run: dotnet fake build -f deploy.fsx

  push-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Push to server
        uses: dokku/github-action@v1
        with:
          git_remote_url: ${{ secrets.GIT_REMOTE_URL}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}