name: 'ci'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:  
  build-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build libraries        
        run: docker build . --file Dockerfile.ci.libraries
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Integration Tests         
        run: docker run --name dhsysdb-dev -p "2424:5432" -e POSTGRES_PASSWORD=postgres -d postgres && docker build . -f Dockerfile.ci.test -t apitest && docker run --network=host apitest:latest
  build-desktop:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v1      
      - name: Run FAKE.build CI script from Docker
        run: docker build . --file Dockerfile.ci.desktop --tag adnanioricce:$(date +%s) --build-arg GITHUB_TOKEN=${{ secrets.PERSONAL_TOKEN }}
