name: 'ci'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:  
  build-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build libraries        
        run: docker build . --file Dockerfile.ci.libraries
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Integration Tests         
        run: docker run --name dhsysdb -p "5432:5432" -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dhsysdb -d postgres && docker build . -f Dockerfile.ci.test -t apitest && docker run --link dhsysdb -e DH_CONNECTION_STRING="User ID=postgres;Password=postgres;Host=dhsysdb;Database=dhsysdb;Port=5432;" apitest:latest