name: 'ci'
on:
  push:
    branches:      
      - development
  pull_request:
    branches:
      - master
jobs:
  build-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: build libraries        
        run: docker build . --file Dockerfile.ci.libraries
  test-api:
<<<<<<< HEAD
    runs-on: ubuntu-latest    
=======
    runs-on: ubuntu-latest  
>>>>>>> d5e4fbc810b2101b87771c692104c6309e1a396d
    services:
      postgres:
        image: postgres
        env:         
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dhsysdb
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2                        
      - name: Build Integration Tests Docker Image
        run: docker build . -f Dockerfile.ci.test -t adnanioricce/dhsysapitest
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - name: Push Image
        run: docker push adnanioricce/dhsysapitest
      - name: Build Integration Tests Docker Image
        run: docker build . -f Dockerfile.ci.test -t adnanioricce/dhsysapitest
      - name: Push Image
        run: docker push adnanioricce/dhsysapitest
      - name: Run Integration Tests
        run: docker run --link dhsysdb adnanioricce/dhsysapitest
        env:
          POSTGRES_HOST: dhsysdb
          POSTGRES_PORT: 5432
