name: 'ci'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run FAKE.build CI script from Docker        
        run: docker build . --file Dockerfile.ci.api --tag adnanioricce:$(date +%s)
  build-desktop:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v1      
      - name: Run FAKE.build CI script from Docker
        run: docker build . --file Dockerfile.ci.desktop --tag adnanioricce:$(date +%s)

