name: 'ci'
on:
  push:
    branches:      
      - development
  pull_request:
    branches:
      - master
jobs:
  build-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: build libraries        
        run: docker build . --file Dockerfile.ci.libraries --build-arg BRANCH_NAME=${GITHUB_REF##*/}
