name: 'cd'
on:
  push:
    branches:      
      - master            
jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run deploy process
        run: mkdir tmp && docker build ./tmp -f Dockerfile.deploy.libraries --build-arg BRANCH_NAME=${GITHUB_REF##*/} --build-arg DHSYS_NUGET_KEY=${{ secrets.DHSYS_NUGET_KEY }} --build-arg=GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}