name: 'cd'
on:
  push:
    branches:      
      - master      
      - development
jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: mkdir tmp && docker build ./tmp -f Dockerfile.deploy.libraries --build-arg BRANCH_NAME=${GITHUB_REF##*/} 