name: 'cd'
on:
  push:
    branches:      
      - master      
      - development
jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2      
      - uses: actions/setup-dotnet@v1
      - uses: actions/setup-gitversion@v1.0.0
        with:
          dotnet: '5.0.x'
      - name: Install FAKE
        run: dotnet tool restore
      - name: Run script
        run: dotnet fake build -f deploy.fsx  