name: 'cd'
on:
  push:
    branches:      
      - master      
jobs:
  deploy-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run deploy process
        run: docker build . -f src/Libraries/Dockerfile.ci.libraries --build-arg DHSYS_NUGET_KEY=${{ secrets.DHSYS_NUGET_KEY }} --build-arg=GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run deploy process
        run: docker build . -f src/Libraries/Dockerfile.ci.api -t adnanioricce/dhsys
      - name: Authenticate user on Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Image to Docker Hub
        run: docker image push adnanioricce/dhsys
      - name: Upload changes on stage server
        run: git remote add deploy ${{ secrets.STAGE_SERVER_ADDRESS }} ; git push deploy main:master