name: 'cd'
on:
  push:
    branches:      
      - master      
      - development
jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet: '5.0.x'
      - name: Install FAKE
        run: dotnet tool restore
      - name: Run deploy script
        run: dotnet fake build -f deploy.fsx
